import { create } from 'zustand';

export type LanguageType = 'en' | 'hi' | 'mr';

export interface LanguageStore {
  language: LanguageType;
  setLanguage: (lang: LanguageType) => void;
  t: (key: string) => string;
}

const translations: Record<LanguageType, Record<string, string>> = {
  en: {
    app_title: 'ARIHANT GOLD',
    explore_categories: 'EXPLORE CATEGORIES',
    trending_collection: 'TRENDING COLLECTION',
    view_all: 'View All',
    shop_collection: 'Shop Collection',
    my_profile: 'MY PROFILE',
    my_orders: 'My Orders History',
    account_ledger: 'My Account & Ledger Balance',
    services: 'Polishing & Repair Services',
    help_support: 'Help & Store Enquiries',
    about_us: 'About Arihant Gold',
    app_theme: 'App Appearance',
    change_language: 'App Language',
    logout: 'Log Out of Account',
    admin_portal: 'Admin Management Portal',
    access_code: 'Change Access Code',
    search_placeholder: 'Search 24K forming necklaces, bangles...',
    home: 'Home',
    shop: 'Shop Catalog',
    wishlist: 'Wishlist',
    cart: 'Shopping Cart',
    profile: 'Profile',
    add_to_cart: 'ADD TO CART',
    buy_now: 'BUY NOW',
    price: 'Price',
    category: 'Category',
    style: 'Style',
    stock: 'In Stock',
    reviews: 'Customer Reviews',
    checkout: 'Proceed to Checkout',
    total_amount: 'Total Amount',
    subtotal: 'Subtotal',
    shipping_fee: 'Shipping Fee',
    free: 'FREE',
    place_order: 'PLACE ORDER NOW',
    pay_now: 'PAY NOW',
    billing_address: 'Billing Address',
    payment_method: 'Payment Method',
    login_title: 'ARIHANT GOLD LOGIN',
    login_sub: 'Log in with your account or Google OAuth to open the app catalog.',
    email_or_phone: 'EMAIL OR PHONE',
    password: 'PASSWORD',
    login_btn: 'LOG IN & ENTER APP',
    google_login: 'SIGN IN WITH GOOGLE OAUTH',
    create_account: 'Create Account',
    dont_have_account: "Don't have an account?",
    register_title: 'CREATE NEW ACCOUNT',
    full_name: 'FULL NAME',
    phone_number: '10-DIGIT PHONE NUMBER',
    email_address: 'EMAIL ADDRESS (OPTIONAL)',
    register_btn: 'REGISTER & ACCESS APP',
    already_have_account: 'Already have an account?',
    access_gate_title: 'ARIHANT GOLD ACCESS ID GATE',
    access_gate_sub: 'Please enter your assigned Access ID code to unlock exclusive catalog.',
    enter_access_id: 'ENTER ACCESS ID KEY',
    unlock_catalog: 'UNLOCK EXCLUSIVE CATALOG',
    order_status: 'Order Status',
    order_id: 'Order ID',
    pending: 'Pending',
    processing: 'Processing',
    completed: 'Completed',
    delivered: 'Delivered',
    cancelled: 'Cancelled',
    heritage_story: 'OUR HERITAGE STORY',
    flagship_store: 'FLAGSHIP BOUTIQUE STORE',
    customer_support: 'CUSTOMER SUPPORT',
    send_enquiry: 'SEND STORE ENQUIRY',
    submit_enquiry: 'SUBMIT STORE ENQUIRY',
    faqs: 'FREQUENTLY ASKED QUESTIONS',
    vip_access: 'VIP PRIVATE ACCESS',
  },
  hi: {
    app_title: 'अरिहंत गोल्ड एंड लक्ज़री',
    explore_categories: 'श्रेणियां देखें',
    trending_collection: 'ट्रेंडिंग कलेक्शन',
    view_all: 'सभी देखें',
    shop_collection: 'कलेक्शन खरीदें',
    my_profile: 'मेरी प्रोफ़ाइल',
    my_orders: 'मेरे ऑर्डर का इतिहास',
    account_ledger: 'मेरा खाता और लेज़र बैलेंस',
    services: 'पॉलिशिंग और मरम्मत सेवाएं',
    help_support: 'सहायता और पूछताछ',
    about_us: 'अरिहंत गोल्ड के बारे में',
    app_theme: 'ऐप का स्वरूप',
    change_language: 'ऐप की भाषा',
    logout: 'खाते से लॉग आउट करें',
    admin_portal: 'एडमिन प्रबंधन पोर्टल',
    access_code: 'एक्सेस कोड बदलें',
    search_placeholder: '24K फार्मिंग हार, चूड़ियां खोजें...',
    home: 'होम',
    shop: 'दुकान कैटलॉग',
    wishlist: 'विशलिस्ट',
    cart: 'शॉपिंग कार्ट',
    profile: 'प्रोफ़ाइल',
    add_to_cart: 'कार्ट में जोड़ें',
    buy_now: 'अभी खरीदें',
    price: 'मूल्य',
    category: 'श्रेणी',
    style: 'शैली',
    stock: 'स्टॉक में उपलब्ध',
    reviews: 'ग्राहक समीक्षा',
    checkout: 'चेकआउट करें',
    total_amount: 'कुल राशि',
    subtotal: 'उप-कुल',
    shipping_fee: 'शिपिंग शुल्क',
    free: 'मुफ़्त',
    place_order: 'ऑर्डर प्लेस करें',
    pay_now: 'अभी भुगतान करें',
    billing_address: 'बिलिंग पता',
    payment_method: 'भुगतान का तरीका',
    login_title: 'अरिहंत गोल्ड लॉगिन',
    login_sub: 'कैटलॉग देखने के लिए अपने खाते या Google OAuth से लॉगिन करें।',
    email_or_phone: 'ईमेल या फोन नंबर',
    password: 'पासवर्ड',
    login_btn: 'लॉगिन करें और प्रवेश करें',
    google_login: 'गूगल से लॉगिन करें',
    create_account: 'नया खाता बनाएं',
    dont_have_account: 'क्या आपके पास खाता नहीं है?',
    register_title: 'नया खाता पंजीकृत करें',
    full_name: 'पूरा नाम',
    phone_number: '10-अंकों का फोन नंबर',
    email_address: 'ईमेल पता (वैकल्पिक)',
    register_btn: 'रजिस्टर करें और प्रवेश करें',
    already_have_account: 'क्या आपका खाता पहले से है?',
    access_gate_title: 'अरिहंत गोल्ड एक्सेस आईडी गेट',
    access_gate_sub: 'एक्सक्लूसिव कैटलॉग अनलॉक करने के लिए अपना एक्सेस आईडी दर्ज करें।',
    enter_access_id: 'एक्सेस आईडी कुंजी दर्ज करें',
    unlock_catalog: 'कैटलॉग अनलॉक करें',
    order_status: 'ऑर्डर स्थिति',
    order_id: 'ऑर्डर आईडी',
    pending: 'लंबित',
    processing: 'प्रक्रिया में',
    completed: 'पूर्ण',
    delivered: 'डिलीवर किया गया',
    cancelled: 'रद्द',
    heritage_story: 'हमारी विरासत कहानी',
    flagship_store: 'मुख्य बुटीक स्टोर',
    customer_support: 'ग्राहक सहायता',
    send_enquiry: 'स्टोर पूछताछ भेजें',
    submit_enquiry: 'पूछताछ जमा करें',
    faqs: 'अक्सर पूछे जाने वाले प्रश्न',
    vip_access: 'वीआईपी निजी एक्सेस',
  },
  mr: {
    app_title: 'अरिहंत गोल्ड अँड लक्झरी',
    explore_categories: 'वर्गवारी शोधा',
    trending_collection: 'ट्रेंडिंग कलेक्शन',
    view_all: 'सर्व पहा',
    shop_collection: 'कलेक्शन खरेदी करा',
    my_profile: 'माझी प्रोफाइल',
    my_orders: 'माझा ऑर्डर इतिहास',
    account_ledger: 'माझे खाते आणि लेजर बाकी',
    services: 'पॉलिशिंग आणि दुरुस्ती सेवा',
    help_support: 'मदत आणि चौकशी',
    about_us: 'अरिहंत गोल्ड बद्दल',
    app_theme: 'ॲपचे स्वरूप',
    change_language: 'ॲपची भाषा',
    logout: 'खात्यातून लॉग आउट करा',
    admin_portal: 'ॲडमिन व्यवस्थापन पोर्टल',
    access_code: 'ॲक्सेस कोड बदला',
    search_placeholder: '24K फॉर्मिंग हार, बांगड्या शोधा...',
    home: 'मुख्य पृष्ठ',
    shop: 'दुकान कॅटलॉग',
    wishlist: 'विशलिस्ट',
    cart: 'खरेदी कार्ट',
    profile: 'प्रोफाइल',
    add_to_cart: 'कार्टमध्ये जोडा',
    buy_now: 'आत्ताच खरेदी करा',
    price: 'किंमत',
    category: 'वर्गवारी',
    style: 'शैली',
    stock: 'स्टॉकमध्ये उपलब्ध',
    reviews: 'ग्राहक पुनरावलोकने',
    checkout: 'चेकआउट करा',
    total_amount: 'एकूण रक्कम',
    subtotal: 'उप-एकूण',
    shipping_fee: 'शिपिंग शुल्क',
    free: 'मोफत',
    place_order: 'ऑर्डर प्लेस करा',
    pay_now: 'आत्ताच पेमेंट करा',
    billing_address: 'बिलिंग पत्ता',
    payment_method: 'पेमेंट पद्धत',
    login_title: 'अरिहंत गोल्ड लॉगिन',
    login_sub: 'कॅटलॉग पाहण्यासाठी आपल्या खात्यावरून किंवा Google OAuth वरून लॉगिन करा.',
    email_or_phone: 'ईमेल किंवा फोन नंबर',
    password: 'पासवर्ड',
    login_btn: 'लॉगिन करा आणि प्रवेश करा',
    google_login: 'गूगलवरून लॉगिन करा',
    create_account: 'नवीन खाते तयार करा',
    dont_have_account: 'तुमचे खाते नाही का?',
    register_title: 'नवीन खाते नोंदणी करा',
    full_name: 'पूर्ण नाव',
    phone_number: '10-अंकी फोन नंबर',
    email_address: 'ईमेल पत्ता (पर्यायी)',
    register_btn: 'नोंदणी करा आणि प्रवेश करा',
    already_have_account: 'तुमचे खाते आधीच आहे का?',
    access_gate_title: 'अरिहंत गोल्ड ॲक्सेस आयडी गेट',
    access_gate_sub: 'एक्सक्लुझिव्ह कॅटलॉग अनलॉक करण्यासाठी आपला ॲक्सेस आयडी टाका.',
    enter_access_id: 'ॲक्सेस आयडी की टाका',
    unlock_catalog: 'कॅटलॉग अनलॉक करा',
    order_status: 'ऑर्डर स्थिती',
    order_id: 'ऑर्डर आयडी',
    pending: 'प्रलंबित',
    processing: 'प्रक्रियेत',
    completed: 'पूर्ण',
    delivered: 'वितरित',
    cancelled: 'रद्द',
    heritage_story: 'आमची वारसा कथा',
    flagship_store: 'मुख्य बुटीक स्टोअर',
    customer_support: 'ग्राहक मदत केंद्र',
    send_enquiry: 'स्टोअर चौकशी पाठवा',
    submit_enquiry: 'चौकशी सबमिट करा',
    faqs: 'सतत विचारले जाणारे प्रश्न',
    vip_access: 'VIP प्रायव्हेट ॲक्सेस',
  },
};

export const useLanguageStore = create<LanguageStore>((set, get) => ({
  language: 'en',
  setLanguage: (lang) => set({ language: lang }),
  t: (key) => {
    const lang = get().language;
    return translations[lang]?.[key] || translations['en'][key] || key;
  },
}));
