android.useAndroidX=true
android.enableJetifier=true
org.gradle.jvmargs=-Xmx2048m -XX:MaxMetaspaceSize=512m
HERMES_ENABLED=true
newArchEnabled=false
MYAPP_RELEASE_STORE_FILE=arihant-gold-release.keystore
MYAPP_RELEASE_KEY_ALIAS=arihant-gold-key
MYAPP_RELEASE_STORE_PASSWORD=ArihantGold@2024
MYAPP_RELEASE_KEY_PASSWORD=ArihantGold@2024
